language: nix
sudo: false

cache: false

matrix:
  include:
  - {}
  - os: osx

script:
- nix-build -j8
deploy:
  provider: releases
  api_key:
    secure: HgG0wburBoUnULjqK3I86k9ZNVLks4/WXPicd7rn2z8HbFpFv/QVN6882hYbsWQd3xhe+Q+hTfXMSL2lbZpiEKAB3UgQclJMP84A42DyvS6RE5a+kwl/wVVNXQh4sNlzuApTSzjYZZkYvroyakqsucCRg7u56eN4NM2VvrDUuJw=
  file: "$TRAVIS_BUILD_DIR/${TRAVIS_OS_NAME}-nix.tar.gz"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
before_deploy:
- cp "$TRAVIS_BUILD_DIR/result/bin/pandoc-crossref" "$TRAVIS_BUILD_DIR/pandoc-crossref"
- chown "$USER" "$TRAVIS_BUILD_DIR/pandoc-crossref"
- chmod u+w "$TRAVIS_BUILD_DIR/pandoc-crossref"
- nix-shell --command "patchelf --set-interpreter /lib64/ld-linux-x86-64.so.2 $TRAVIS_BUILD_DIR/pandoc-crossref"
- nix-shell --command "pandoc -s -t man docs/index.md -o $TRAVIS_BUILD_DIR/pandoc-crossref.1"
- tar czf "$TRAVIS_BUILD_DIR/${TRAVIS_OS_NAME}-nix.tar.gz" -C "$TRAVIS_BUILD_DIR" "./pandoc-crossref.1" "./pandoc-crossref"
